version: "3.8"
networks:
  #network-zabbix:
  #  external: true
  #  name: network-zabbix
  app-network:
    name: app-network
    driver: bridge

services:
  api:
    depends_on:
      database:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5181:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING:-Server=database,1433;Database=Fase1TechChallenge;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;}
    networks:
      - app-network
    #  - network-zabbix
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    networks:
      - app-network
      #  - network-zabbix
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
