name: CI Build and Tests

on:
  push:
    branches:
      - integration-tests
  pull_request:
    branches:
      - integration-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            **/bin/Release/net8.0/

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: .

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release --filter "Category!=Integration"

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: .

      - name: Run Integration Tests
        run: dotnet test --no-build --configuration Release --filter "Category=Integration"
